# Generated by Django 6.1.1 on 2026-10-08 08:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.CharField(choices=[('all_grades', 'All Grades (1-O Level)'), ('o_level', 'O Level'), ('o_a_level', 'O/A Level'), ('university', 'University Level')], max_length=20)),
                ('price_40_min', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_60_min', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('level__in', ['all_grades', 'o_level', 'o_a_level', 'university'])), name='subject_level_valid'), models.CheckConstraint(condition=models.Q(('price_40_min__gte', 0)), name='subject_price_40_min_gte_0'), models.CheckConstraint(condition=models.Q(('price_60_min__gte', 0)), name='subject_price_60_min_gte_0')],
            },
        ),
    ]
