# Generated by Django 6.1.1 on 2026-10-08 08:50

import classes.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=9)),
                ('time', models.TimeField(validators=[classes.models.validate_full_hour])),
                ('duration', models.PositiveSmallIntegerField(choices=[(40, '40 minutes'), (60, '60 minutes')])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_classes', to='classes.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_classes', to='classes.subject')),
            ],
            options={
                'verbose_name_plural': 'weekly classes',
                'constraints': [models.UniqueConstraint(fields=('day', 'time'), name='weekly_class_unique_timeslot', violation_error_message='This timeslot is already booked.'), models.CheckConstraint(condition=models.Q(('day__in', ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'])), name='weekly_class_day_valid'), models.CheckConstraint(condition=models.Q(('duration__in', [40, 60])), name='weekly_class_duration_valid'), models.CheckConstraint(condition=models.Q(('time__in', [datetime.time(0, 0), datetime.time(1, 0), datetime.time(2, 0), datetime.time(3, 0), datetime.time(4, 0), datetime.time(5, 0), datetime.time(6, 0), datetime.time(7, 0), datetime.time(8, 0), datetime.time(9, 0), datetime.time(10, 0), datetime.time(11, 0), datetime.time(12, 0), datetime.time(13, 0), datetime.time(14, 0), datetime.time(15, 0), datetime.time(16, 0), datetime.time(17, 0), datetime.time(18, 0), datetime.time(19, 0), datetime.time(20, 0), datetime.time(21, 0), datetime.time(22, 0), datetime.time(23, 0)])), name='weekly_class_time_full_hour')],
            },
        ),
    ]
