# Generated by Django 6.1.1 on 2026-10-08 12:51

from django.db import migrations

LEVELS = [
    ("o_level", "O Level"),
    ("a_level", "A Level"),
    ("all_levels", "All Levels (1-O Level)"),
    ("university", "University Level"),
]

# Old single level code -> the codes of the levels that replace it.
OLD_TO_NEW = {
    "all_grades": ["all_levels"],
    "o_level": ["o_level"],
    "o_a_level": ["o_level", "a_level"],
    "university": ["university"],
}

# The closest old code for a subject that is left with a single level.
NEW_TO_OLD = {
    "o_level": "o_level",
    "a_level": "o_a_level",
    "all_levels": "all_grades",
    "university": "university",
}


def seed_levels_and_copy(apps, schema_editor):
    Level = apps.get_model("classes", "Level")
    Subject = apps.get_model("classes", "Subject")

    levels = {}
    for code, name in LEVELS:
        levels[code], _ = Level.objects.get_or_create(
            code=code, defaults={"name": name}
        )

    for subject in Subject.objects.all():
        subject.levels.add(*[levels[code] for code in OLD_TO_NEW[subject.level]])


def copy_back(apps, schema_editor):
    # Lossy: the old column holds one code, so a subject keeps a single level.
    Subject = apps.get_model("classes", "Subject")

    for subject in Subject.objects.prefetch_related("levels"):
        codes = [level.code for level in subject.levels.all()]
        if {"o_level", "a_level"} <= set(codes):
            subject.level = "o_a_level"
        else:
            # A subject with no level, or only levels added later, still
            # needs a code the restored constraint accepts.
            subject.level = next(
                (NEW_TO_OLD[code] for code in codes if code in NEW_TO_OLD),
                "all_grades",
            )
        subject.save(update_fields=["level"])


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_level_subject_levels'),
    ]

    operations = [
        # Removed here, not with the column in 0006, so that unapplying
        # restores the codes before the constraint is put back.
        migrations.RemoveConstraint(
            model_name='subject',
            name='subject_level_valid',
        ),
        migrations.RunPython(seed_levels_and_copy, copy_back),
    ]
