# Generated by Django 6.1.1 on 2026-10-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_seed_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
    ]
