# Generated by Django 6.1.1 on 2026-10-08 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_remove_subject_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyclass',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_classes', to='classes.level'),
        ),
    ]
