# Generated by Django 6.1.1 on 2026-10-08 14:27

import classes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_weeklyclass_level_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(validators=[classes.models.validate_full_hour])),
                ('completed', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_lessons', to='classes.level')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial_lesson', to='classes.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_lessons', to='classes.subject')),
            ],
            options={
                'ordering': ['starts_at'],
                'constraints': [models.UniqueConstraint(fields=('starts_at',), name='trial_lesson_unique_starts_at', violation_error_message='This timeslot is already booked.'), models.CheckConstraint(condition=models.Q(('starts_at__minute', 0), ('starts_at__second', 0)), name='trial_lesson_starts_at_full_hour')],
            },
        ),
    ]
