# Generated by Django 6.1.1 on 2026-10-09 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_triallesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid slug: lowercase letters, digits and hyphens.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*\\Z')]),
            preserve_default=False,
        ),
    ]
